name: Auto Terraform Deploy

on:
  push:
    branches:
      - dev
      - test
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  find_changed_modules:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch history to compare against previous commit

      - name: Get changed Terraform module directories
        id: get_changed_dirs
        run: |
          # Get the list of changed directories
          CHANGED_DIRS=$(git diff --name-only HEAD^ HEAD | xargs -n1 dirname | grep module/ | awk -F'/' '{print $2}' | sort -u  | tr '\n' ' ' | xargs)
          echo "Changed directories: $CHANGED_DIRS"
          if [[ "$CHANGED_DIRS" != "" ]]; then
            echo "changed_modules=${CHANGED_DIRS}" >> "$GITHUB_OUTPUT"
          else
            echo "No module changes detected."
            echo "changed_modules=None" >> "$GITHUB_OUTPUT"
          fi

      - name: Set matrix for affected modules
        id: set_matrix
        run: |  
          if [[ "${{ steps.get_changed_dirs.outputs.changed_modules }}" == "None" ]]; then
            echo "matrix=None" >> "$GITHUB_OUTPUT"
          else
            # Convert the list of changed modules into a JSON array for the matrix
            MODULES_JSON="{\"module\": $(echo '${{ steps.get_changed_dirs.outputs.changed_modules }}' | tr '\n' ' ' | jq -R -s -c 'split(" ") | map(select(length > 0))')}"
            echo "Matrix JSON: $MODULES_JSON"
            echo "matrix=$MODULES_JSON" >> "$GITHUB_OUTPUT"
          fi

  terraform:
    needs: find_changed_modules
    if: needs.find_changed_modules.outputs.matrix != 'None'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.find_changed_modules.outputs.matrix) }}
    environment:
      name: ${{ (github.ref_name == 'main' || github.head_ref == 'main') && 'prod'  || (github.ref_name == 'test' || github.head_ref == 'test') && 'test' || 'dev' }}
    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: https://accounts.azuredatabricks.net
      DATABRICKS_ACCOUNT_ID: ${{ secrets.DATABRICKS_ACCOUNT_ID }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_ACCOUNT_ADMIN_CLIENT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true  # 👈 This tells Terraform to use OIDC natively
      ARM_USE_CLI: false   # 👈 Prevents Terraform from trying to use the CLI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      
      - name: Terraform Init
        id: init
        run: terraform init -backend-config=env-config/${{ vars.ENV }}-backend.conf
        working-directory: module/${{ matrix.module }}

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -var-file="env-config/${{ vars.ENV }}.tfvars"env-config/
        working-directory: module/${{ matrix.module }}

      - name: Terraform Apply
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve -var-file="env-config/${{ vars.ENV }}.tfvars"
        working-directory: module/${{ matrix.module }}